### ISSUE TITLE
Incomplete table of values for the Helm chart

### ISSUE THREAD

**Issue by lindhe** [NVIDIA/cloud-native-docs#50]
I found that the chart values documented [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#chart-customization-options) are incomplete. They are at least missing the `devicePlugin` object as documented [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html#configuring-time-slicing-before-installing-the-nvidia-gpu-operator). Would be great if that was updated! 👍

This was originally posted in https://github.com/NVIDIA/gpu-operator/issues/698 and was moved here.

**Comment by mikemckiernan** [comment]
Hello @lindhe!  Thank you for opening this issue.  At this point, I don't plan to cover every field in the chart.  Can you tell me more about which fields in the device plugin section that you needed to use?

**Comment by lindhe** [comment]
The particular value I needed to set was `devicePlugin.config.name`.

I completely get you! It _sucks_ to manually create tables for values and then have the never ending struggle of keeping them up-to-date. If you do plan on having tables at all, I would recommend checking out this: https://github.com/bitnami/readme-generator-for-helm

Otherwise, was long as the `values.yaml` file is publicly available and easy to find, having tables are just a nice-to-have. Is there an easier way to browse it than running a `helm pull` on the chart and exploring it locally?

**Comment by lindhe** [comment]
If the tables will not be complete, I would much appreciate a small note saying something along the lines of:

> ℹ️ Note: this table is not complete. For the complete list of values, please see https://github.com/NVIDIA/some-repo

**Comment by mikemckiernan** [comment]
@lindhe, thank you for your patience and suggestions.

I spoke with the maintainers of the GPU Operator chart and the consensus was that the most likely use case for setting `devicePlugin.config` is to configure time slicing.  I opened #65 to add the field to the table so it's findable and to add a link to the time slicing procedure.

If you had a different use case, please share here or in the GPU Operator repo and we'll try to address it.

**Comment by lindhe** [comment]
Time slicing is exactly my use-case. Thanks for the response!
