### ISSUE TITLE
missing documentation on the use of custom config for device plugin

### ISSUE THREAD

**Issue by asm582** [NVIDIA/cloud-native-docs#65]
Hello,

We are trying to point the device plugin to use a custom config using configMap. 

In the documentation such an option is not provided [here](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#chart-customization-options) but the helm chart has such an option [here](https://github.com/NVIDIA/gpu-operator/blob/58afc29d12da9a40f8204883686fa915b60533ba/deployments/gpu-operator/values.yaml#L271).

Can we update the docs with an example?

**Comment by mikemckiernan** [comment]
Hello @asm582!  Thank you for opening the issue and pointing out that `devicePlugin.config` is missing from the table of chart customization options.

I checked with the engineering folks (maintainers of the values.yaml that you referenced) and the consensus was that most customers would use that field to configure time slicing.  As we get new features that can be configured with the same option, I can update the docs.

My proposed fix is to add the field to the table (so you don't think we're gaslighting you) and provide a link to the time slicing procedure.  PTAL at [PR #69].

If you have a different use case, please share here or in the GPU Operator repo and we'll try to address it.
